version: '3.8'

services:
  backend:
    build: ./warehouse-backend
    container_name: warehouse-backend
    restart: always
    ports:
      - "5003:5002"
    volumes:
      - ./warehouse-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 400M

  frontend:
    build: ./warehouse-frontend
    container_name: warehouse-frontend
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./warehouse-frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 700M

networks:
  app-network:
    driver: bridge 