version: '3.8'

services:
  backend:
    build: ./warehouse-backend
    container_name: warehouse-backend
    restart: always
    ports:
      - "5001:5002"
    volumes:
      - ./warehouse-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build: ./warehouse-frontend
    container_name: warehouse-frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 